//! Default filetype patterns derived from the pygments lexer registry.
//!
//! The list is generated by `scripts/gen_filetypes.py`; rerun that script
//! whenever the pygments dependency in `pyproject.toml` is bumped.

mod data {
    include!("filetypes_data.rs");
}

pub use data::DEFAULT_FILETYPE_PATTERNS;

/// Returns the default filetype glob patterns (e.g. `*.rs`, `*.py`) used to
/// decide which blobs to include when `--all-filetypes` is not set.
pub fn default_patterns() -> &'static [&'static str] {
    DEFAULT_FILETYPE_PATTERNS
}
