# This formula is generated by .github/workflows/release.yml from published
# release artifacts. Do not replace these placeholders manually.
class GitOfTheseus < Formula
  desc "Analyze the evolution of a Git repository's code over time"
  homepage "https://github.com/eapolinario/git-of-theseus"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/eapolinario/git-of-theseus/releases/download/v0.5.1/git-of-theseus-v0.5.1-aarch64-apple-darwin.tar.gz"
      sha256 "7d95db2ff0987a3e28ca70b24fab86d8c7ce087b187ad6b19ff3d3fec65d58dc"
    end

    on_intel do
      url "https://github.com/eapolinario/git-of-theseus/releases/download/v0.5.1/git-of-theseus-v0.5.1-x86_64-apple-darwin.tar.gz"
      sha256 "8235b311674746bcfac128c16b442479d495c42b81718d0485cb721cfcbeba2a"
    end
  end

  def install
    archive_dir = Dir["git-of-theseus-v#{version}-*-apple-darwin"].fetch(0)
    bin.install Dir["#{archive_dir}/git-of-theseus-*"]
  end

  test do
    %w[analyze line-plot stack-plot survival-plot].each do |subcommand|
      assert_match "Usage", shell_output("#{bin}/git-of-theseus-#{subcommand} --help")
    end
  end
end
