#!/usr/bin/env python3
"""Regenerate crates/got-core/src/filetypes_data.rs from pygments.

The Rust port mirrors the default_filetypes set built dynamically in
git_of_theseus/analyze.py. We snapshot it once and embed it as a static
slice in got-core so the Rust crate does not need a Python runtime.

Run this whenever the pygments dependency in pyproject.toml is bumped.
"""
from pathlib import Path

import pygments.lexers

# Keep in sync with git_of_theseus/analyze.py:IGNORE_PYGMENTS_FILETYPES
IGNORE_PYGMENTS_FILETYPES = {
    "*.json", "*.md", "*.ps", "*.eps", "*.txt", "*.xml", "*.xsl",
    "*.rss", "*.xslt", "*.xsd", "*.wsdl", "*.wsf", "*.yaml", "*.yml",
}


def main() -> None:
    ft: set[str] = set()
    for _, _, filetypes, _ in pygments.lexers.get_all_lexers():
        ft.update(filetypes)
    ft -= IGNORE_PYGMENTS_FILETYPES

    out_path = (
        Path(__file__).resolve().parent.parent
        / "crates" / "got-core" / "src" / "filetypes_data.rs"
    )
    lines = [
        "// This file is auto-generated by scripts/gen_filetypes.py from the",
        "// pygments lexer registry. Do not edit by hand; rerun the script",
        "// to refresh after upgrading pygments.",
        "// Filetypes pygments classifies as configuration/documentation are",
        "// excluded to match git_of_theseus/analyze.py:IGNORE_PYGMENTS_FILETYPES.",
        "",
        "pub const DEFAULT_FILETYPE_PATTERNS: &[&str] = &[",
    ]
    for pattern in sorted(ft):
        escaped = pattern.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines.append("];")
    lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"wrote {len(ft)} patterns to {out_path}")


if __name__ == "__main__":
    main()
